name: Destroy Test Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to Destroy (e.g., test, staging)'
        required: true
        type: string

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::863518431435:role/AWS-Credentials-for-GitHub-Role-6m3NmxeVglm0
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform -chdir=src/iac init

      - name: Terraform Destroy
        run: terraform -chdir=src/iac destroy -auto-approve
